require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OrderTasksController do

  # This should return the minimal set of attributes required to create a valid
  # OrderTask. As you add validations to OrderTask, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrderTasksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all order_tasks as @order_tasks" do
      order_task = OrderTask.create! valid_attributes
      get :index, {}, valid_session
      assigns(:order_tasks).should eq([order_task])
    end
  end

  describe "GET show" do
    it "assigns the requested order_task as @order_task" do
      order_task = OrderTask.create! valid_attributes
      get :show, {:id => order_task.to_param}, valid_session
      assigns(:order_task).should eq(order_task)
    end
  end

  describe "GET new" do
    it "assigns a new order_task as @order_task" do
      get :new, {}, valid_session
      assigns(:order_task).should be_a_new(OrderTask)
    end
  end

  describe "GET edit" do
    it "assigns the requested order_task as @order_task" do
      order_task = OrderTask.create! valid_attributes
      get :edit, {:id => order_task.to_param}, valid_session
      assigns(:order_task).should eq(order_task)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OrderTask" do
        expect {
          post :create, {:order_task => valid_attributes}, valid_session
        }.to change(OrderTask, :count).by(1)
      end

      it "assigns a newly created order_task as @order_task" do
        post :create, {:order_task => valid_attributes}, valid_session
        assigns(:order_task).should be_a(OrderTask)
        assigns(:order_task).should be_persisted
      end

      it "redirects to the created order_task" do
        post :create, {:order_task => valid_attributes}, valid_session
        response.should redirect_to(OrderTask.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved order_task as @order_task" do
        # Trigger the behavior that occurs when invalid params are submitted
        OrderTask.any_instance.stub(:save).and_return(false)
        post :create, {:order_task => {  }}, valid_session
        assigns(:order_task).should be_a_new(OrderTask)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OrderTask.any_instance.stub(:save).and_return(false)
        post :create, {:order_task => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested order_task" do
        order_task = OrderTask.create! valid_attributes
        # Assuming there are no other order_tasks in the database, this
        # specifies that the OrderTask created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OrderTask.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => order_task.to_param, :order_task => { "these" => "params" }}, valid_session
      end

      it "assigns the requested order_task as @order_task" do
        order_task = OrderTask.create! valid_attributes
        put :update, {:id => order_task.to_param, :order_task => valid_attributes}, valid_session
        assigns(:order_task).should eq(order_task)
      end

      it "redirects to the order_task" do
        order_task = OrderTask.create! valid_attributes
        put :update, {:id => order_task.to_param, :order_task => valid_attributes}, valid_session
        response.should redirect_to(order_task)
      end
    end

    describe "with invalid params" do
      it "assigns the order_task as @order_task" do
        order_task = OrderTask.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OrderTask.any_instance.stub(:save).and_return(false)
        put :update, {:id => order_task.to_param, :order_task => {  }}, valid_session
        assigns(:order_task).should eq(order_task)
      end

      it "re-renders the 'edit' template" do
        order_task = OrderTask.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OrderTask.any_instance.stub(:save).and_return(false)
        put :update, {:id => order_task.to_param, :order_task => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested order_task" do
      order_task = OrderTask.create! valid_attributes
      expect {
        delete :destroy, {:id => order_task.to_param}, valid_session
      }.to change(OrderTask, :count).by(-1)
    end

    it "redirects to the order_tasks list" do
      order_task = OrderTask.create! valid_attributes
      delete :destroy, {:id => order_task.to_param}, valid_session
      response.should redirect_to(order_tasks_url)
    end
  end

end
